# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders_manager.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_manager.Product')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.RemoveField(
            model_name='orderrow',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderrow',
            name='product',
        ),
        migrations.DeleteModel(
            name='OrderRow',
        ),
    ]
